restore-gradle-cache: &restore-gradle-cache
  restore_cache:
    keys:
      - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - v1-dependencies-

save-gradle-cache: &save-gradle-cache
  save_cache:
    paths:
      - ~/.gradle
    key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}

version: 2
jobs:
  build-test:
    working_directory: ~/code
    docker:
      - image: zenika/kotlin:1.3-eap-jdk10-slim

    steps:
      - checkout

      - <<: *restore-gradle-cache
      - run: ./gradlew compileTestKotlin
      - <<: *save-gradle-cache

      - run:
          name: Run Tests
          command: ./gradlew clean test

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-test